// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Js_mapperRt = require("bs-platform/lib/js/js_mapperRt.js");
var DeccoHelper$SeamonsterStudiosReason = require("@seamonster-studios/reason/src/utils/DeccoHelper.bs.js");

function MakePV(Config) {
  return Config;
}

var jsMapperConstantArray = [
  /* tuple */[
    17727,
    "On"
  ],
  /* tuple */[
    3951439,
    "Off"
  ]
];

function tToJs(param) {
  return Js_mapperRt.binarySearch(2, param, jsMapperConstantArray);
}

function tFromJs(param) {
  return Js_mapperRt.revSearch(2, jsMapperConstantArray, param);
}

var Status = DeccoHelper$SeamonsterStudiosReason.MakePV({
      tToJs: tToJs,
      tFromJs: tFromJs,
      name: "Status"
    });

var statusWorks = Status;

var statusBroken = Status;

exports.MakePV = MakePV;
exports.Status = Status;
exports.statusWorks = statusWorks;
exports.statusBroken = statusBroken;
/* Status Not a pure module */
